name: Build and publish juicer-board to npm

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    name: Release juicer-board as npm package

    strategy:
      matrix:
        platform:
          - ubuntu-latest
        node-version:
          - 22.x

    runs-on: ${{ matrix.platform }}

    permissions:
      packages: write
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Verify package signatures
        run: npm audit signatures

      - name: Run tests
        run: npm run test --if-present

      - name: Build the app
        run: npm run build --if-present

      - name: Release with semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
